package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCategory<M extends BaseCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setGrade(java.lang.Integer grade) {
		set("grade", grade);
		return (M)this;
	}
	
	public java.lang.Integer getGrade() {
		return getInt("grade");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setIsMenu(java.lang.Boolean isMenu) {
		set("isMenu", isMenu);
		return (M)this;
	}
	
	public java.lang.Boolean getIsMenu() {
		return get("isMenu");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setTreePath(java.lang.String treePath) {
		set("treePath", treePath);
		return (M)this;
	}
	
	public java.lang.String getTreePath() {
		return getStr("treePath");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	public java.lang.Long getParentId() {
		return getLong("parentId");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setPageTemplate(java.lang.String pageTemplate) {
		set("pageTemplate", pageTemplate);
		return (M)this;
	}
	
	public java.lang.String getPageTemplate() {
		return getStr("pageTemplate");
	}

}
