package com.cms.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("kf_ad", "id", Ad.class);
		arp.addMapping("kf_ad_position", "id", AdPosition.class);
		arp.addMapping("kf_admin", "id", Admin.class);
		arp.addMapping("kf_category", "id", Category.class);
		arp.addMapping("kf_content", "id", Content.class);
		arp.addMapping("kf_friend_link", "id", FriendLink.class);
		arp.addMapping("kf_gb", "id", Gb.class);
		arp.addMapping("kf_member", "id", Member.class);
		arp.addMapping("kf_product_category", "id", ProductCategory.class);
	}
}

